---
all:
  hosts:
    portal:
      ansible_host: 10.31.61.11

    edu-hermes:
      ansible_host: 10.31.61.14

    bpm-server:
      ansible_host: 10.31.61.15

    dw-server:
      ansible_host: 10.31.61.13

    iac-server:
      ansible_host: 10.31.62.148

    tf-sample-server:
      ansible_host: 10.31.61.217
      ansible_ssh_private_key_file: ~/.ssh/ansible_deploy_key

  vars:
    ansible_connection: ssh
    ansible_user: karelialabadmin
    ansible_password: "VerySecretEndeed123!"

  children:
    linux_servers:
      hosts:
        portal:
        edu-hermes:
        bpm-server:
        dw-server:

    web_servers:
      hosts:
        portal:

    application_servers:
      hosts:
        edu-hermes:
        bpm-server:

    automation_servers:
      hosts:
        iac-server:

    test_servers:
      hosts:
        tf-sample-server:

